### PR TITLE
Put GAP version into a variable; update to GAP 4.10.1; use `make bootstrap-pkg-minimal`

### LINKED ISSUE #14: Update this to GAP 4.10.1 or even 4.10.2?

### PR DESCRIPTION
**Pull request by fingolfin**
Resolves #14

### CODE REVIEW

**Comment by olexandr-konovalov** [comment]
Well, our main container for the GAP latest official release is https://github.com/gap-system/gap-docker, while this repository is unused for a while. Still is a good thing to update it too, in case someone may be interested in using a minimalistic container.

**Comment by fingolfin** [comment]
@alex-konovalov but gap-docker is based on (inherits from) gap-docker-base which in turn inherits from `gap-container`. Something does not add up here.

**Comment by fingolfin** [comment]
@alex-konovalov it looks to me as if two versions of GAP are built for `gap-docker`: first `gap-container` builds GAP 4.10.0, then based on that, `gap-docker-base` compiles some packages, and then based on that `gap-docker` overwrites all that previous work with a fresh build of GAP 4.10.1. That doesn't seem sensible. Perhaps `gap-docker` then is meant to be based directly on a stock Ubuntu image?

**Comment by olexandr-konovalov** [comment]
`gap-docker-base` has no automated builds since it requires more resources than Docker Hub provides. In the past, that was a bottleneck since each release someone (@sebasguts) had to manually do that. So we decided that we just have `gap-docker-base` as a container with dependencies that GAP requires, and use it as a base container for all other ones:
- gap-docker
- gap-docker-stable-4.X
- gap-master

**Comment by olexandr-konovalov** [comment]
Also, gap-docker-base does not compile some packages. In only install dependencies for some packages.

**Comment by fingolfin** [comment]
@alex-konovalov that may all be true, but it seems to be orthogonal to what I wrote? I clearly see `FROM gapsystem/gap-container` in https://github.com/gap-system/gap-docker-base/blob/master/Dockerfile ?

**Review by sebasguts — APPROVED** [review]
Looks good!

**Comment by olexandr-konovalov** [comment]
@fingolfin that means that https://github.com/gap-system/gap-docker-base/blob/master/Dockerfile could actually be based directly on a stock Ubuntu image.

**Review by olexandr-konovalov — APPROVED** [review]

**Pull request merged**
